theme: jekyll-theme-cayman
gem "github-pages", group: :jekyll_plugins
title: Federico Moreno
description: Licenciado en Economía Empresarial, Universidad Torcuato Di Tella. Estudiante de la Maestría de Data Mining de la UBA
description: Estudiante de la Maestría de Data Mining de la UBA


