theme: jekyll-theme-cayman
gem "github-pages", group: :jekyll_plugins
title: Federico Moreno
description: Licenciado en Economía Empresarial, Universidad Torcuato Di Tella.
Estudiante del Maestría de Data Mining de la UBA


